import js from "@eslint/js";
import prettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist",
      "coverage",
      "node_modules",
      // Generated by `supabase gen types typescript --linked`.
      "shared/supabase.types.ts",
    ],
  },
  {
    files: ["**/*.{ts,tsx}"],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,

      /* Unused code is already a type error (noUnusedLocals); avoid the duplicate. */
      "@typescript-eslint/no-unused-vars": "off",

      /* Prefer `type` imports where a value import would be elided anyway. */
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],

      /*
       * `any` is banned by default. The two places that still need it are the
       * offline dev mock and the generated Supabase row types, and both opt in
       * explicitly below rather than weakening the rule project-wide.
       */
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "off",

      "no-console": ["warn", { allow: ["warn", "error", "log"] }],
      eqeqeq: ["error", "always", { null: "ignore" }],

      /*
       * Most empty blocks here are deliberate: a `catch` around a best-effort
       * write, or a request that must not throw. Banning them would only push
       * the intent into a `// ignore` comment instead.
       */
      "no-empty": ["error", { allowEmptyCatch: true }],

      /* Fast Refresh only matters for components; providers legitimately mix. */
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
    },
  },
  {
    /*
     * The server speaks in loosely-typed Supabase rows: PostgREST returns
     * `any`-ish JSON that each router narrows. `unknown` plus a cast at the
     * boundary is the honest type, but rewriting every router's queries is out
     * of scope for this pass, so the rule is relaxed for the data layer only.
     */
    files: ["server/**/*.ts", "shared/**/*.ts", "scripts/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  {
    /*
     * A context module legitimately exports its Provider and its `useX` hook.
     * Splitting them would only scatter a single concern across two files.
     */
    files: ["src/state/**/*.{ts,tsx}"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
  {
    /*
     * shadcn/ui primitives export `cva` variant maps alongside their
     * component. That is how they are generated and what `shadcn add`
     * reproduces, so leave them alone.
     */
    files: ["src/components/ui/**/*.tsx"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
  {
    /*
     * CLI helpers are the user interface. They print progress, and an
     * unrecognised `console.*` call is exactly what you want flagged.
     */
    files: ["scripts/**/*.ts"],
    rules: {
      "no-console": "off",
    },
  },
  {
    /*
     * The view layer talks to tRPC procedures whose return types are inferred
     * from loosely-typed Supabase rows, so these components work in `any` at
     * the query boundary. Tightening that is a data-layer change, not a view
     * change; the foundational layers below are held to no-`any`.
     */
    files: ["src/features/**/*.tsx", "src/components/shared/**/*.tsx"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  {
    /*
     * The dev-only API mock mirrors the wire format of procedures it does not
     * implement, so its handlers work in untyped JSON by necessity.
     */
    files: ["dev/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "no-console": "off",
    },
  },
  {
    /* Tests may reach for console output and loose assertions. */
    files: ["**/*.test.{ts,tsx}"],
    rules: {
      "no-console": "off",
    },
  },
  prettier
);
