#!/usr/bin/env python3
"""
Fetch self-hosted woff2 fonts (Google Fonts, OFL-licensed) into `public/fonts/`.

Why self-host
-------------
The storefront loaded two families (Fraunces 500/600/700, Plus Jakarta Sans
400/500/600/700) from fonts.googleapis.com: a render-blocking third-party
chain (DNS + TLS + CSS + font files) on every first visit — the worst kind of
weight on mid-range Android/4G, our primary visitor profile. Self-hosted files
are same-origin, immutable-cacheable, and preloaded for the two critical
weights. Latin subsets only: the site ships English copy (Hinglish phrases are
latin-script); anything outside latin falls back to the system stack declared
alongside each family.

Both families are SIL Open Font License 1.1 — self-hosting is permitted.
Keep the license note: fonts.css emits it as a comment.

Re-run only to change families/weights/subsets:

    python3 scripts/fetch-fonts.py

Then rebuild: `@font-face` lives in `src/fonts.css` (imported by
`src/styles.css`) and preloads live in `index.html`.
"""

from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONTS_DIR = ROOT / "public" / "fonts"
CSS_OUT = ROOT / "src" / "fonts.css"

CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700"
    "&family=Plus+Jakarta+Sans:wght@400;500;600;700"
    "&display=swap"
)
# A woff2-capable UA so the CSS returns woff2 (not TTF) URLs.
UA = (
    "Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 "
    "Chrome/120 Safari/537.36"
)


def slug(family: str, weight: str) -> str:
    return f"{family.lower().replace(' ', '')}-{weight}.woff2"


def main() -> None:
    req = urllib.request.Request(CSS_URL, headers={"User-Agent": UA})
    css = urllib.request.urlopen(req, timeout=30).read().decode("utf-8")

    # Split into @font-face blocks; keep only the `latin` subset of each
    # family/weight (identified by the U+0000-00FF unicode-range tail).
    blocks = re.findall(r"/\*\s*([a-z-]+)\s*\*/\s*@font-face\s*{([^}]+)}", css)
    wanted = [b for b in blocks if b[0] == "latin"]
    if not wanted:
        print("fetch-fonts: no latin @font-face blocks found — aborting.")
        sys.exit(1)

    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    out = [
        "/* Self-hosted subset of Google Fonts (OFL 1.1):",
        " * Fraunces 500/600/700 + Plus Jakarta Sans 400/500/600/700, latin only.",
        " * Generated by scripts/fetch-fonts.py — do not hand-edit. */",
    ]
    for _subset, body in wanted:
        family = re.search(r"font-family:\s*'([^']+)'", body).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", body).group(1)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", body).group(1)
        fname = slug(family, weight)
        dest = FONTS_DIR / fname
        if not dest.exists():
            data = urllib.request.urlopen(
                urllib.request.Request(url, headers={"User-Agent": UA}), timeout=60
            ).read()
            dest.write_bytes(data)
            print(f"fetch-fonts: downloaded {fname} ({len(data) // 1024} KiB)")
        else:
            print(f"fetch-fonts: kept existing {fname}")
        out.append(
            "@font-face {\n"
            f"  font-family: '{family}';\n"
            "  font-style: normal;\n"
            f"  font-weight: {weight};\n"
            "  font-display: swap;\n"
            f"  src: url('/fonts/{fname}') format('woff2');\n"
            "  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, "
            "U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, "
            "U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;\n"
            "}"
        )
    CSS_OUT.write_text("\n".join(out) + "\n")
    print(f"fetch-fonts: wrote {CSS_OUT.relative_to(ROOT)} ({len(wanted)} faces)")


if __name__ == "__main__":
    main()
